version: '2'
services:

  sqlserver:
    hostname: sqlserver
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SQLServerPass1
