version: '2'
services:
  kudu:
    hostname: kudu
    image: 'usuresearch/kudu-docker-slim:release-v1.8.0-1'
    ports:
      - '18050:8050'
      - '18051:8051'
      - '17050:7050'
      - "${KUDU_MASTER_RPC_PORT}:7051"
    environment:
      - "KUDU_MASTER_EXTRA_OPTS=--default_num_replicas 1 --webserver_advertised_addresses ${DOCKER_HOST_IP}:18051 --rpc_advertised_addresses ${DOCKER_HOST_IP}:${KUDU_MASTER_RPC_PORT}"
      - "KUDU_TSERVER_EXTRA_OPTS=--webserver_advertised_addresses ${DOCKER_HOST_IP}:18050 --rpc_advertised_addresses ${DOCKER_HOST_IP}:17050"
