version: '2'
services:
  kudu1:
    hostname: kudu1
    image: 'usuresearch/kudu-docker-slim:release-v1.8.0-1'
    ports:
      - '18050:8050'
      - '18051:8051'
      - '17050:7050'
      - "${KUDU_MASTER_RPC_PORT}:7051"
    environment:
      - "KUDU_MASTER_EXTRA_OPTS=--webserver_advertised_addresses ${DOCKER_HOST_IP}:18051 --rpc_advertised_addresses ${DOCKER_HOST_IP}:${KUDU_MASTER_RPC_PORT}"
      - "KUDU_TSERVER_EXTRA_OPTS=--webserver_advertised_addresses ${DOCKER_HOST_IP}:18050 --rpc_advertised_addresses ${DOCKER_HOST_IP}:17050"

  kudu2:
    hostname: kudu2
    image: 'usuresearch/kudu-docker-slim'
    ports:
      - '28050:8050'
      - '27050:7050'
    environment:
      - "KUDU_MASTER=${DOCKER_HOST_IP}:${KUDU_MASTER_RPC_PORT}"
      - "KUDU_TSERVER_EXTRA_OPTS=--webserver_advertised_addresses ${DOCKER_HOST_IP}:28050 --rpc_advertised_addresses ${DOCKER_HOST_IP}:27050"

  kudu3:
    hostname: kudu3
    image: 'usuresearch/kudu-docker-slim'
    ports:
      - '38050:8050'
      - '37050:7050'
    environment:
      - "KUDU_MASTER=${DOCKER_HOST_IP}:${KUDU_MASTER_RPC_PORT}"
      - "KUDU_TSERVER_EXTRA_OPTS=--webserver_advertised_addresses ${DOCKER_HOST_IP}:38050 --rpc_advertised_addresses ${DOCKER_HOST_IP}:37050"
