# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

workflows:
  version: 2
  dist-compile:
    jobs:
      - linux-build
      - linux-build-options
      - linux-adapters
      - macos-build
      - format-check
      - header-check
      - linux-benchmarks-basic

  # Daily documentation update
  nightly:
    triggers:
      - schedule:
         cron: "0 3 * * *"
         filters:
           branches:
             only:
               - main
    jobs:
      - doc-gen-job
      - linux-fuzzer-run

  # Hourly build on weekdays
  weekday:
    triggers:
      - schedule:
          cron: "0 0,4,8,12,16,20 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - linux-build
      - linux-build-release
      - linux-build-options
      - linux-adapters
      - macos-build

commands:
  update-submodules:
    steps:
      - run:
          name: "Update Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

  pre-steps:
    steps:
      - checkout
      - update-submodules
      - run:
          name: "Setup Environment"
          command: |
            # Calculate ccache key.
            git show -s --format=%cd --date="format:%Y%m%d" $(git merge-base origin/main HEAD) | tee merge-base-date

            # Set up xml gtest output. 
            mkdir -p /tmp/test_xml_output/
            echo "export XML_OUTPUT_FILE=\"/tmp/test_xml_output/\"" >> $BASH_ENV

            # Set up ccache configs.
            mkdir -p .ccache
            echo "export CCACHE_DIR=$(realpath .ccache)" >> $BASH_ENV
            ccache -sz -M 5Gi
            source /opt/rh/gcc-toolset-9/enable
      - restore_cache:
          name: "Restore CCache Cache"
          keys:
            - velox-ccache-debug-{{ arch }}-{{ checksum "merge-base-date" }}

  post-steps:
    steps:
      - save_cache:
          name: "Save CCache Cache"
          key: velox-ccache-debug-{{ arch }}-{{ checksum "merge-base-date" }}
          paths:
            - .ccache/
      - store_artifacts:
          path: '_build/debug/.ninja_log'
      - store_test_results:
          path: '/tmp/test_xml_output/'

executors:
  build:
    docker:
      - image : prestocpp/velox-avx-circleci:mikesh-20220717
    resource_class: 2xlarge
    environment:
        CC:  /opt/rh/gcc-toolset-9/root/bin/gcc
        CXX: /opt/rh/gcc-toolset-9/root/bin/g++
  check:
    docker:
      - image : prestocpp/velox-check:mikesh-20210609
  doc-gen:
    docker:
      - image : prestocpp/velox-circleci:sagarm-20220131

jobs:
  macos-build:
    macos:
      xcode: "12.5.1"
    resource_class: large
    steps:
      - checkout
      - update-submodules
      - restore_cache:
          name: "Restore Dependency Cache"
          # The version number in the key can be incremented
          # to manually avoid the case where bad dependencies
          # are cached, and has no other meaning.
          # If you update it, be sure to update save_cache too.
          key: velox-circleci-macos-deps-v1-{{ checksum ".circleci/config.yml" }}-{{ checksum "scripts/setup-macos.sh" }}
      - run:
          name: "Install dependencies"
          command: |
            set -xu
            if [[ ! -e ~/deps ]]; then
              mkdir ~/deps ~/deps-src
              curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ~/deps
              PATH=~/deps/bin:${PATH} DEPENDENCY_DIR=~/deps-src INSTALL_PREFIX=~/deps PROMPT_ALWAYS_RESPOND=n ./scripts/setup-macos.sh
              rm -rf ~/deps/.git ~/deps/Library/Taps/  # Reduce cache size by 70%.
            fi
      - save_cache:
          name: "Save Dependency Cache"
          # The version number in the key can be incremented
          # to manually avoid the case where bad dependencies
          # are cached, and has no other meaning.
          # If you update it, be sure to update restore_cache too.
          key: velox-circleci-macos-deps-v1-{{ checksum ".circleci/config.yml" }}-{{ checksum "scripts/setup-macos.sh" }}
          paths:
            - ~/deps
      - run:
          name: "Calculate merge-base date for CCache"
          command: git show -s --format=%cd --date="format:%Y%m%d" $(git merge-base origin/main HEAD) | tee merge-base-date
      - restore_cache:
          name: "Restore CCache cache"
          keys:
            - velox-ccache-debug-{{ arch }}-{{ checksum "merge-base-date" }}
      - run:
          name: "Build on MacOS"
          command: |
            export PATH=~/deps/bin:~/deps/opt/bison/bin:~/deps/opt/flex/bin:${PATH}
            mkdir -p .ccache
            export CCACHE_DIR=$(pwd)/.ccache
            ccache -sz -M 5Gi
            export OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)
            cmake -B _build/debug -GNinja -DTREAT_WARNINGS_AS_ERRORS=1 -DENABLE_ALL_WARNINGS=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=~/deps -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DFLEX_INCLUDE_DIR=~/deps/opt/flex/include
            ninja -C _build/debug
            ccache -s
          no_output_timeout: 1h
      - save_cache:
          name: "Save CCache cache"
          key: velox-ccache-debug-{{ arch }}-{{ checksum "merge-base-date" }}
          paths:
            - .ccache/

  linux-build:
    executor: build
    steps:
      - pre-steps
      - run:
          name: "Build"
          command: |
            make debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8 EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_ARROW=ON"
            ccache -s
          no_output_timeout: 1h
      - run:
          name: "Run Unit Tests"
          command: |
            cd _build/debug && ctest -j 16 -VV --output-on-failure
          no_output_timeout: 1h
      - store_test_results:
          path: /tmp/test_xml_output/
      - run:
          name: "Run Fuzzer Tests"
          command: |
            make fuzzertest NUM_THREADS=10
          no_output_timeout: 5m
      - run:
         name: "Run Example Binaries"
         command: |
           find _build/debug/velox/examples/ -maxdepth 1 -type f -executable -exec "{}" \;
      - post-steps

  linux-build-release:
    executor: build
    steps:
      - pre-steps
      - run:
          name: Build
          command: |
            make release NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
            ccache -s
          no_output_timeout: 1h
      - run:
          name: "Run Unit Tests"
          command: |
            cd _build/release && ctest -j 16 -VV --output-on-failure
          no_output_timeout: 1h
      - post-steps

  linux-benchmarks-basic:
    executor: build
    environment:
      CONBENCH_URL: https://velox-conbench.voltrondata.run/
    steps:
      - pre-steps
      - run:
          name: "Build Benchmarks"
          command: |
            make benchmarks-basic-build NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
            ccache -s
      - run:
          name: "Install Conbench, Benchalerts, and Veloxbench"
          command: |
            # upgrade python to 3.8 for this job
            yum install -y python38
            pip3.8 install conbench
            pip3.8 install git+https://github.com/conbench/benchalerts.git@0.2.1
            pip3.8 install scripts/veloxbench
      - run:
          name: "Run Benchmarks"
          command: |
            # get to the directory with benchmarks
            cd scripts/veloxbench/veloxbench

            # setup .conbench file
            touch .conbench
            echo "url: $CONBENCH_URL" >> .conbench
            echo "email: $CONBENCH_EMAIL" >> .conbench
            echo "password: $CONBENCH_PASSWORD" >> .conbench
            echo "host_name: CircleCI-runner" >> .conbench

            # Figure out the run name and run reason
            if [[ $CIRCLE_BRANCH == 'main' ]]; then
              # Currently, the names of runs to be included in Conbench history must
              # start with 'commit:'
              # (https://github.com/conbench/conbench/issues/350)
              # This way we can keep track of performance over time on the main branch
              # separately from pull request branches and manual runs.

              run_name="commit: $(git rev-parse HEAD)"
              run_reason='commit'
            else
              run_name="pull request $CIRCLE_PR_NUMBER: $(git rev-parse HEAD)"
              run_reason='pull request'
            fi

            conbench cpp-micro --run-name="$run_name" --run-reason="$run_reason"
      - run:
          name: "Analyze Benchmark Regressions and Post to Github"
          command: |
            export GITHUB_APP_PRIVATE_KEY=$(echo $GITHUB_APP_PRIVATE_KEY_ENCODED | base64 -d)
            python3.8 scripts/benchmark-github-status.py --z-score-threshold 50
      - post-steps

  # Build with different options
  linux-build-options:
    executor: build
    steps:
      - pre-steps
      - run:
          name: "Build Velox Minimal"
          command: |
            make min_debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=16
            ccache -s
          no_output_timeout: 1h
      - run:
          name: "Build Velox Without Testing"
          command: |
            make clean
            make debug EXTRA_CMAKE_FLAGS="-DVELOX_BUILD_TESTING=OFF" NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=16
            ccache -s
          no_output_timeout: 1h
      - post-steps

  linux-adapters:
    executor: build
    steps:
      - pre-steps
      - run:
          name: "Install Adapter Dependencies"
          command: |
            mkdir ~/adapter-deps ~/adapter-deps/install
            source /opt/rh/gcc-toolset-9/enable
            set -xu
            DEPENDENCY_DIR=~/adapter-deps PROMPT_ALWAYS_RESPOND=n ./scripts/setup-adapters.sh
      - run:
          name: "Install Minio Server"
          command: |
            set -xu
            cd ~/adapter-deps/install/bin/
            wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20220526054841.0.0.x86_64.rpm
            rpm -i minio-20220526054841.0.0.x86_64.rpm
            rm minio-20220526054841.0.0.x86_64.rpm
      - run:
          name: "Install Hadoop Dependency"
          command: |
            set -xu
            yum -y install java-1.8.0-openjdk
      - run:
          name: Build
          command: |
            make release EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_ARROW=ON -DVELOX_ENABLE_PARQUET=ON -DVELOX_ENABLE_HDFS=ON -DVELOX_ENABLE_S3=ON -DVELOX_ENABLE_SUBSTRAIT=ON" AWSSDK_ROOT_DIR=~/adapter-deps/install NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8
            ccache -s
          no_output_timeout: 1h
      - run:
          name: "Run Unit Tests"
          command: |
            export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
            export HADOOP_ROOT_LOGGER="WARN,DRFA"
            export LIBHDFS3_CONF=$(pwd)/.circleci/hdfs-client.xml
            export HADOOP_HOME='/usr/local/hadoop'
            export PATH=~/adapter-deps/install/bin:/usr/local/hadoop/bin:${PATH}
            cd _build/release && ctest -j 16 -VV --output-on-failure
          no_output_timeout: 1h
      - post-steps

  linux-fuzzer-run:
    executor: build
    steps:
      - pre-steps
      - run:
          name: Build
          command: |
            make debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=8 EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_ARROW=ON"
            ccache -s
          no_output_timeout: 1h
      - run:
          # Run Fuzzer, save the output to /tmp/fuzzer.log, and upload the file
          # as job artifact to make it convenient for users to inspect it -
          # these logs can also be quite large. Always prints the last 1k lines to
          # the job output for context.
          name: "Run Fuzzer Tests"
          command: |
            make fuzzertest NUM_THREADS=16 FUZZER_DURATION_SEC=600 FUZZER_SEED=${RANDOM} \
              > /tmp/fuzzer.log 2>&1 || ( \
                tail -n 1000 /tmp/fuzzer.log;
                echo "FAIL: Fuzzer run failed, logs saved to \"/tmp/fuzzer.log\" and uploaded" \
                     "as job artifact (check the \"Artifacts\" tab above).";
                exit 1; \
              )
            tail -n 1000 /tmp/fuzzer.log
            echo -e "\n\nFuzzer run finished successfully. Logs saved as job artifact " \
                 "(check the \"Artifacts\" tab above)."
          no_output_timeout: 20m
      - store_artifacts:
          path: '/tmp/fuzzer.log'
      - post-steps

  format-check:
    executor: check
    steps:
      - checkout
      - run:
          name: Check formatting
          command: |
            if ! make format-check; then
              make format-fix
              echo -e "\n==== Apply using:"
              echo "patch -p1 \<<EOF"
              git --no-pager diff
              echo "EOF"
              false
            fi

  header-check:
    executor: check
    steps:
      - checkout
      - run:
          name: Check license headers
          command: |
            if ! make header-check; then
              make header-fix
              echo -e "\n==== Apply using:"
              echo "patch -p1 \<<EOF"
              git --no-pager diff
              echo "EOF"
              false
            fi

  doc-gen-job:
    executor: doc-gen
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ed:40:13:bc:d0:3d:28:26:98:cb:90:31:cc:d3:f1:6b"
      - run:
          name: "Build docs and update gh-pages"
          command: |
            git config --global user.email "velox@users.noreply.github.com"
            git config --global user.name "velox"
            git checkout main
            make -C velox/docs html
            git checkout gh-pages
            cp -R velox/docs/_build/html/* docs
            git add docs
            if [ -n "$(git status --porcelain)" ]
            then
              git commit -m "Update documentation"
              git push
            fi
