services:

  presto-master:
    image: 'imjalpreet/centos7-oj8-openldap:latest'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh singlenode-ldap run
    extra_hosts:
       - "${LDAP_SERVER_HOST}:${LDAP_SERVER_IP}"
    ports:
      - '8443:8443'
    volumes:
      - ../../../conf/presto/etc/ldap-authenticator.properties:/docker/volumes/conf/presto/etc/password-authenticator.properties
      - ${OVERRIDE_JDK_DIR}:/docker/volumes/overridejdk

  application-runner:
    image: 'imjalpreet/centos7-oj8-openldap:latest'
    environment:
      - TEMPTO_PROFILE_CONFIG_FILE=/docker/volumes/conf/tempto/tempto-configuration-for-docker-ldap.yaml
      - CLI_ARGUMENTS=--server https://presto-master:8443 --keystore-path /etc/openldap/certs/coordinator.jks --keystore-password testldap

  ldapserver:
    image: 'imjalpreet/centos7-oj8-openldap:latest'
