version: '2'
services:

  presto-master:
    volumes:
      - ../../../conf/presto/etc/environment-specific-catalogs/singlenode-hdfs-impersonation/hive.properties:/docker/volumes/conf/presto/etc/catalog/hive.properties
