version: '2'
services:

  kafka:
    hostname: kafka
    image: spotify/kafka
    ports:
      - 9092:9092
      - 2181:2181
    command: |
       bash -xeuo pipefail -c "
          sed -i 's/#delete.topic.enable=true/delete.topic.enable=true/' /opt/kafka_2.11-0.10.1.0/config/server.properties
          exec supervisord -n
       "
