apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-catalog
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- range $name, $properties := .Values.catalog }}
  {{ $name }}.properties: |-
    {{- $properties | nindent 4 }}
  {{- end }}
