# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build & Push Docker Images

on:
  pull_request:
    paths:
      - scripts/*.dockfile
      - scripts/*.dockerfile
      - scripts/setup-*.sh
      - .github/workflows/docker.yml
      - docker-compose.yml
  push:
    branches: [main]
    paths:
      - scripts/*.dockfile
      - scripts/*.dockerfile
      - scripts/setup-*.sh
      - .github/workflows/docker.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  linux:
    name: "Build and Push ${{ matrix.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check
            file: "scripts/check-container.dockfile"
            tags: "ghcr.io/facebookincubator/velox-dev:check"
          - name: Centos 9
            file: "scripts/centos.dockerfile"
            tags: "ghcr.io/facebookincubator/velox-dev:centos9"
          - name: Dev
            file: "scripts/ubuntu-22.04-cpp.dockerfile"
            args: ""
            tags: "ghcr.io/facebookincubator/velox-dev:ubuntu-22.04"

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: "${{ matrix.file }}"
          build-args: "${{ matrix.args }}"
          push: ${{ github.repository == 'facebookincubator/velox' && github.event_name != 'pull_request'}}
          tags: "${{ matrix.tags }}"

  linux-needs:
    name: "Build and Push ${{ matrix.name }}"
    needs: linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Adapters
            file: "scripts/adapters.dockerfile"
            tags: "ghcr.io/facebookincubator/velox-dev:adapters"
          - name: Presto Java
            file: "scripts/prestojava-container.dockerfile"
            args: "PRESTO_VERSION=0.288"
            tags: "ghcr.io/facebookincubator/velox-dev:presto-java"
          - name: Spark server
            file: "scripts/spark-container.dockerfile"
            args: "SPARK_VERSION=3.5.1"
            tags: "ghcr.io/facebookincubator/velox-dev:spark-server"

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: "${{ matrix.file }}"
          build-args: "${{ matrix.args }}"
          push: ${{ github.repository == 'facebookincubator/velox' && github.event_name != 'pull_request'}}
          tags: "${{ matrix.tags }}"
